stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u joaomoraski -p $DOCKER_HUB_ACCESS_TOKEN

build-app:
  stage: build
  script:
    - docker build -t joaomoraski/easycontacts:latest .
    - echo "Build Ok!!"
    - docker push joaomoraski/easycontacts:latest

unit-tests:
  stage: test
  script:
      - docker run --rm joaomoraski/easycontacts:latest ./vendor/bin/phpunit tests --testdox
      - echo "All tests passed!"


deploy-prod:
  stage: deploy
  script:
    - chmod 400 $FILE_UBUNTU_RUNNER
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker login -u joaomoraski -p $DOCKER_HUB_ACCESS_TOKEN"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker pull joaomoraski/easycontacts:latest"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker stop easycontacts || true && docker rm easycontacts || true"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker run -d --name easycontacts -p 80:80 -p 443:443 joaomoraski/easycontacts:latest"
    - echo "Deploy Ok!"
  environment: production
