stages:
  - build
  - test
  - deploy

# If i understand right, this make the docker more faster
variables:
  DOCKER_DRIVER: overlay2

# Running the docker image
services:
  - docker:dind

# Execute the docker login before
before_script:
  - docker login -u joaomoraski -p $DOCKER_HUB_ACCESS_TOKEN

# Build the docker image
build-app:
  stage: build
  script:
    - composer update
    - composer install
    - composer dump-autoload
    - echo "Composer update/install/dump-autoload Ok!✅"
    - docker build -t joaomoraski/easycontacts:latest .
    - echo "Docker Image Build Ok!✅"
    - docker push joaomoraski/easycontacts:latest
    - echo "Docker Push Ok!✅"

unit-tests-logic:
  stage: test
  script:
    - docker run --rm joaomoraski/easycontacts:latest ./vendor/bin/phpunit tests/contactTests --testdox
    - echo "All tests passed!✅"

unit-tests-utils:
  stage: test
  script:
    - docker run --rm joaomoraski/easycontacts:latest ./vendor/bin/phpunit tests/utilsTests --testdox
    - echo "All tests passed!✅"

deploy-prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  script:
    - chmod 400 $FILE_UBUNTU_RUNNER
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker login -u joaomoraski -p $DOCKER_HUB_ACCESS_TOKEN"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker pull joaomoraski/easycontacts:latest"
    - echo "Docker pull on server Ok!"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker stop easycontacts || true && docker rm easycontacts || true"
    - ssh -i $FILE_UBUNTU_RUNNER -o "StrictHostKeyChecking No" ubuntu@web.easycontacts.com "docker run -d --name easycontacts -p 80:80 -p 443:443 joaomoraski/easycontacts:latest"
    - echo "Docker deploy on server Ok!"
  environment: production
