# .readthedocs.yaml

version: 2

# Definindo a imagem base do Docker para construir a documentação
build:
  os: ubuntu-22.04
  tools:
    php: "8.3"
  apt_packages:
    - libxml2-dev
    - libcurl4-openssl-dev
    - libpng-dev
    - libjpeg-dev
    - libfreetype6-dev
    - libonig-dev
    - composer
  jobs:
    pre_build:
      - apt-get update && apt-get install -y \
        libxml2-dev \
        libcurl4-openssl-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libonig-dev
    build:
      - composer install

# Formatos de documentação a serem construídos
formats:
  - html

# Definição de variáveis de ambiente
environment:
  variables:
    DATABASE_HOST: "sql.easycontacts.com"
    DATABASE_USER: "moraski"
    DATABASE_PASSWORD: "moraski"
    DATABASE_NAME: "easyContacts"

# Inclusão de arquivos relevantes
include:
  - README.md
  - docs/**

# Exclusão de arquivos desnecessários
exclude:
  - .git/**
  - .github/**
  - tests/**
